"""Tests for generated-source detection (Task 1)."""

import os
from pathlib import Path
import pytest

from java_codebase_rag.graph.graph_enrich import classify_java_file, GeneratedDetectionConfig, load_generated_detection
from java_codebase_rag.ast.ast_java import parse_java


FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "generated_samples"


def _parse_fixture(filename: str):
    """Helper: parse fixture file, return (source_bytes, ast)."""
    fixture_path = FIXTURE_DIR / filename
    source = fixture_path.read_bytes()
    ast = parse_java(source=source, filename=str(fixture_path))
    return source, ast


class TestGeneratedDetection:
    """Generated-source detection tests."""

    def test_openapi_annotation(self):
        """@Generated(value="org.openapitools.codegen...") → (True, "openapi")."""
        source, ast = _parse_fixture("OpenAPIModel.java")
        generated, generated_by = classify_java_file(source, ast)
        assert generated is True
        assert generated_by == "openapi"

    def test_javax_generated_no_value(self):
        """@Generated with no value → (True, None)."""
        source, ast = _parse_fixture("JavaxGenerated.java")
        generated, generated_by = classify_java_file(source, ast)
        assert generated is True
        assert generated_by is None

    def test_jsonschema2pojo_header(self):
        """jsonschema2pojo banner in header → (True, "jsonschema2pojo")."""
        source, ast = _parse_fixture("JsonSchemaPojo.java")
        generated, generated_by = classify_java_file(source, ast)
        assert generated is True
        assert generated_by == "jsonschema2pojo"

    def test_protobuf_header(self):
        """protobuf-generated banner → (True, "protobuf")."""
        source, ast = _parse_fixture("ProtobufMessage.java")
        generated, generated_by = classify_java_file(source, ast)
        assert generated is True
        assert generated_by == "protobuf"

    def test_handwritten_is_not_generated(self):
        """Plain hand-written type, no markers → (False, None)."""
        source, ast = _parse_fixture("HandWritten.java")
        generated, generated_by = classify_java_file(source, ast)
        assert generated is False
        assert generated_by is None

    def test_config_force_fqn(self):
        """FQN in force_fqns → (True, None) even without markers."""
        source, ast = _parse_fixture("HandWritten.java")
        config = GeneratedDetectionConfig(force_fqns={"com.example.handwritten.HandWritten"})
        generated, generated_by = classify_java_file(source, ast, config=config)
        assert generated is True
        assert generated_by is None

    def test_config_exclude_fqn_wins(self):
        """@Generated present but FQN in exclude_fqns → (False, None)."""
        source, ast = _parse_fixture("OpenAPIModel.java")
        config = GeneratedDetectionConfig(
            exclude_fqns={"com.example.model.OpenAPIModel"}
        )
        generated, generated_by = classify_java_file(source, ast, config=config)
        assert generated is False
        assert generated_by is None

    def test_config_extra_header_pattern(self):
        """Custom header_patterns matches internal banner → (True, None)."""
        # Create a fixture with custom header
        custom_source = b"""
/**
 * Internal code generator - DO NOT EDIT
 * Generated by internal tool v1.0
 */
package com.example.internal;

public class CustomHeader {
    private String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }
}
"""
        ast = parse_java(source=custom_source, filename="CustomHeader.java")
        config = GeneratedDetectionConfig(
            header_patterns=[r"Internal code generator"]
        )
        generated, generated_by = classify_java_file(custom_source, ast, config=config)
        assert generated is True
        assert generated_by is None

    def test_false_positive_misleading_header(self):
        """Hand-written file with generated-like phrase but no signature → (False, None)."""
        # File contains "generated" in a comment but has no @Generated annotation
        # and doesn't match any real generator signature
        misleading_source = b"""
/**
 * Reviewed and generated by the internal team
 *
 * This is a hand-written file with a misleading comment.
 * It should NOT be classified as generated code.
 */
package com.example.handwritten;

public class MisleadingHeader {
    private String value;
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }
}
"""
        ast = parse_java(source=misleading_source, filename="MisleadingHeader.java")
        generated, generated_by = classify_java_file(misleading_source, ast)
        assert generated is False, "Hand-written file should not be classified as generated"
        assert generated_by is None

    def test_precision_qualified_mapstruct_annotation(self):
        """Fully-qualified @javax.annotation.processing.Generated(value="org.mapstruct...") → (True, "mapstruct")."""
        # This tests Fix 1: the value-check must happen before the FQN early-return
        mapstruct_source = b"""
package com.example.mapstruct;

import javax.annotation.processing.Generated;

@Generated(value = "org.mapstruct.ap.MappingProcessor", date = "2025-01-01T00:00:00Z", comments = "MapStruct processor")
public class MapStructMapper {
    public String map(String input) { return input; }
}
"""
        ast = parse_java(source=mapstruct_source, filename="MapStructMapper.java")
        generated, generated_by = classify_java_file(mapstruct_source, ast)
        assert generated is True
        assert generated_by == "mapstruct", f"Expected 'mapstruct' but got '{generated_by}'"

    def test_precision_generated_unrecognized_value(self):
        """@Generated with malformed/unrecognized value → (True, None) (generated detected, family unknown)."""
        unrecognized_source = b"""
package com.example.generated;

import javax.annotation.processing.Generated;

@Generated(value = "com.unknown.FakeProcessor", comments = "Unknown generator")
public class GeneratedUnknown {
    private String value;
}
"""
        ast = parse_java(source=unrecognized_source, filename="GeneratedUnknown.java")
        generated, generated_by = classify_java_file(unrecognized_source, ast)
        assert generated is True, "File with @Generated should be classified as generated"
        assert generated_by is None, "Unrecognized value should yield None for family"


class TestConfigLoading:
    """Config loading tests."""

    def test_empty_config_when_missing(self):
        """Empty config when file missing or section absent."""
        config = load_generated_detection(None)
        assert config == GeneratedDetectionConfig()

    def test_loads_from_yaml(self):
        """Loads generated_detection section from YAML."""
        # Create temp config file
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / ".java-codebase-rag.yml"
            config_path.write_text("""
generated_detection:
  header_patterns:
    - "Generated by internal tool"
  annotation_patterns:
    - "com.example.CustomGenerated"
  force_fqns:
    - "com.example.GeneratedModel"
  exclude_fqns:
    - "com.example.ExcludeMe"
""")

            config = load_generated_detection(tmpdir)
            assert "Generated by internal tool" in config.header_patterns
            assert "com.example.CustomGenerated" in config.annotation_patterns
            assert "com.example.GeneratedModel" in config.force_fqns
            assert "com.example.ExcludeMe" in config.exclude_fqns

    def test_malformed_entry_warns_and_continues(self):
        """Malformed entries stderr-warn and are dropped."""
        import tempfile
        import io
        import sys

        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = Path(tmpdir) / ".java-codebase-rag.yml"
            # Write config with malformed entries (not lists)
            config_path.write_text("""
generated_detection:
  header_patterns: "this should be a list"
  force_fqns: "also should be a list"
""")

            # Capture stderr
            old_stderr = sys.stderr
            sys.stderr = io.StringIO()

            try:
                config = load_generated_detection(tmpdir)
                # Should return empty config for malformed entries
                assert config == GeneratedDetectionConfig()
            finally:
                sys.stderr = old_stderr
