/**
 * This file was generated by jsonschema2pojo.
 *
 * Generation date: 2025-01-15T10:30:00Z
 * Schema: User.json
 */
package com.example.jsonschema;

public class JsonSchemaPojo {
    private String username;
    private String email;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
