package com.example.model;

import io.swagger.annotations.ApiModel;

/**
 * This file was generated by the OpenAPI Generator.
 *
 * OpenAPI Generator version: 7.0.0
 */
@Generated(value = "org.openapitools.codegen.DefaultCodegen", date = "2025-01-15T10:30:00Z")
@ApiModel(description = "Sample API model")
public class OpenAPIModel {
    private String id;
    private String name;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
