// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto
package com.example.protobuf;

/**
 * Protobuf-generated message class.
 */
public final class ProtobufMessage {
    private String id;
    private String data;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}
